# Generated by Django 3.2.18 on 2023-05-15 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_reported'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tags',
        ),
        migrations.AddField(
            model_name='user',
            name='tags',
            field=models.CharField(default='태그', max_length=100),
        ),
    ]
