# Generated by Django 3.2.18 on 2023-05-15 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20230515_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='big_tags',
            field=models.CharField(default='태그', max_length=100),
        ),
    ]
