# Generated by Django 3.2.18 on 2023-05-17 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.CharField(default='태그', max_length=10000),
        ),
        migrations.AlterField(
            model_name='review',
            name='tags',
            field=models.CharField(default='태그', max_length=100000),
        ),
    ]
