# Generated by Django 3.2.18 on 2023-05-10 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='poster_path',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
