# Generated by Django 3.2.18 on 2023-05-12 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='spoiler',
            field=models.BooleanField(default=False, verbose_name='스포일러'),
        ),
        migrations.CreateModel(
            name='ReviewReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('스팸', '스팸'), ('스포일러', '스포일러'), ('해로운 허위 정보 및 폭력 미화', '해로운 허위 정보 및 폭력 미화'), ('신원 파악이 가능한 개인정보 노출', '신원 파악이 가능한 개인정보 노출'), ('기타', '기타')], max_length=100)),
                ('content', models.TextField()),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_report', to='movies.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('스팸', '스팸'), ('스포일러', '스포일러'), ('해로운 허위 정보 및 폭력 미화', '해로운 허위 정보 및 폭력 미화'), ('신원 파악이 가능한 개인정보 노출', '신원 파악이 가능한 개인정보 노출'), ('기타', '기타')], max_length=100)),
                ('content', models.TextField()),
                ('reported_count', models.PositiveIntegerField(default=0)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_report', to='movies.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
