# Generated by Django 3.2.18 on 2023-05-11 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(default='태그', max_length=100),
        ),
    ]
