# Generated by Django 3.2.18 on 2023-05-11 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='platform',
            field=models.CharField(max_length=100),
        ),
    ]
