# Generated by Django 3.2.18 on 2023-05-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20230512_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentreport',
            name='reported_count',
        ),
        migrations.AddField(
            model_name='review',
            name='spoiler',
            field=models.BooleanField(default=False, verbose_name='스포일러'),
        ),
    ]
