# Generated by Django 3.2.18 on 2023-05-10 05:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0002_post_poster_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='want_users',
        ),
        migrations.AddField(
            model_name='post',
            name='want_users',
            field=models.ManyToManyField(related_name='want_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='post',
            name='watching_users',
        ),
        migrations.AddField(
            model_name='post',
            name='watching_users',
            field=models.ManyToManyField(related_name='watching_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
