# Generated by Django 3.2.18 on 2023-05-11 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_post_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='movie_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
