# Generated by Django 3.2.18 on 2023-05-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20230510_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='update_at',
        ),
        migrations.AlterField(
            model_name='post',
            name='releasedate',
            field=models.DateField(),
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
