# Generated by Django 3.2.18 on 2023-05-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20230510_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='nation',
        ),
        migrations.RemoveField(
            model_name='post',
            name='poster_path',
        ),
        migrations.RemoveField(
            model_name='post',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='post',
            name='releasedate',
        ),
        migrations.RemoveField(
            model_name='post',
            name='runningtime',
        ),
        migrations.RemoveField(
            model_name='post',
            name='similarmovies',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='post',
            name='update_at',
        ),
        migrations.RemoveField(
            model_name='review',
            name='tags',
        ),
        migrations.AddField(
            model_name='review',
            name='tags',
            field=models.CharField(default='태그', max_length=100),
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
